import React, {useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const blank={title:'',body:'',due_date:''};
function App(){
 const [items,setItems]=useState([]),[tab,setTab]=useState('task'),[draft,setDraft]=useState(blank),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const drag=useRef(null),title=useRef(null);
 async function api(path,method='GET',body){const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(typeof d.detail==='string'?d.detail:'Could not save. Check your input and try again.');}return r.status===204?null:r.json();}
 async function refresh(){setItems(await api('/items'));}
 useEffect(()=>{refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function act(fn){setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const list=items.filter(i=>i.kind===tab),tasks=items.filter(i=>i.kind==='task'),done=tasks.filter(i=>i.done).length,percent=tasks.length?Math.round(done/tasks.length*100):0;
 function edit(item){setEditing(item);setDraft({title:item.title,body:item.body,due_date:item.due_date||''});title.current.focus();}
 function move(from,to){if(busy||from<0||to<0||to>=list.length||from===to)return;const ids=list.map(i=>i.id);ids.splice(to,0,ids.splice(from,1)[0]);act(()=>api('/order','PUT',{kind:tab,ids}));}
 function submit(e){e.preventDefault();const dueDate=e.currentTarget.elements.namedItem('due_date')?.value;act(async()=>{await api(editing?'/items/'+editing.id:'/items',editing?'PUT':'POST',{...draft,kind:tab,done:!!editing?.done,due_date:tab==='task'?(dueDate||null):null});setDraft(blank);setEditing(null);});}
 const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
 return <div className="shell"><aside><a className="brand" href="/"><span>✓</span>little list<b>.</b></a><div className="workspace">SHARED SPACE</div><nav aria-label="Main navigation">{[['task','☑','Shared tasks'],['note','▤','Notes']].map(([kind,icon,label])=><button key={kind} disabled={busy} className={tab===kind?'selected':''} onClick={()=>{setTab(kind);setDraft(blank);setEditing(null);}}><span>{icon} &nbsp; {label}</span><b>{items.filter(i=>i.kind===kind).length}</b></button>)}</nav><div className="aside-bottom">● &nbsp; Saved after every change<p>A little space to clear your mind.</p></div></aside>
 <main><header><div className="eyebrow">ONE THING AT A TIME</div><div className="heading"><h1>{tab==='task'?'Shared tasks':'Shared notes'}<span>.</span></h1><span className="date">{now.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</span></div><p className="subtitle">{tab==='task'?'Everyone can add, edit, and delete items on this shared list.':'Notes are shared with everyone who opens this app.'}</p></header>
 {tab==='task'&&<div className="progress-card"><div className="progress-symbol">↗</div><div className="progress-content"><div><strong>{tasks.length?`${done} of ${tasks.length} tasks complete`:'A fresh start'}</strong><span>{percent}%</span></div><div className="track"><div style={{width:percent+'%'}}/></div><small>{tasks.length&&done===tasks.length?'All done. Enjoy a little breathing room.':'Small steps count. You’ve got this.'}</small></div></div>}
 {error&&<div role="alert" className="error">{error}<button onClick={()=>act(async()=>{})}>Retry loading</button></div>}
 <section className="composer"><h2>{editing?'Edit '+tab:tab==='task'?'Add a task':'Add a note'}</h2><form onSubmit={submit}><label className="sr-only" htmlFor="title">Title</label><input id="title" ref={title} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder={tab==='task'?'What would you like to get done?':'Give your note a title'} maxLength={200} required disabled={busy||loading}/><label className="sr-only" htmlFor="body">Notes</label><textarea id="body" value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} placeholder={tab==='task'?'Add a little detail (optional)':'Write what’s on your mind…'} maxLength={20000} rows={tab==='task'?2:5} disabled={busy||loading}/><div className="form-footer">{tab==='task'?<label className="due-input">Due date <input name="due_date" type="date" value={draft.due_date} onChange={e=>setDraft({...draft,due_date:e.target.value})} disabled={busy||loading}/></label>:<span className="optional">Your ideas belong here.</span>}<div className="form-actions">{editing&&<button type="button" className="secondary" disabled={busy} onClick={()=>{setDraft(blank);setEditing(null);}}>Cancel</button>}<button className="primary" disabled={busy||loading||!draft.title.trim()}>{busy?'Saving…':editing?'Save changes':tab==='task'?'+ Add task':'+ Add note'}</button></div></div></form></section>
 <section className="list-section" aria-label="Saved items"><div className="list-heading"><h2>{tab==='task'?'Your list':'Your notes'} <span>{list.length}</span></h2><small>Drag to reorder · or use the arrows</small></div>{loading?<div className="empty">Loading your space…</div>:list.length===0?<div className="empty"><div className="empty-icon">{tab==='task'?'✓':'▤'}</div><h3>{tab==='task'?'A little less on your mind.':'Good ideas start somewhere.'}</h3><p>{tab==='task'?'Add your first task above and take it one step at a time.':'Add your first note above. It will be waiting here for you.'}</p></div>:<div className="items">{list.map((item,index)=><article key={item.id} className={'item '+(item.done?'done':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();move(list.findIndex(i=>i.id===drag.current),index);drag.current=null;}}><span className="grip" draggable={!busy} onDragStart={e=>{drag.current=item.id;e.dataTransfer.setData('text/plain',String(item.id));}} onDragEnd={()=>drag.current=null} title="Drag to reorder" aria-hidden="true">⠿</span>{tab==='task'&&<input type="checkbox" aria-label={'Complete '+item.title} checked={!!item.done} disabled={busy} onChange={()=>act(()=>api('/items/'+item.id,'PUT',{...item,done:!item.done}))}/>}<div className="item-content"><button className="item-title" disabled={busy} onClick={()=>edit(item)}>{item.title}</button>{item.body&&<p>{item.body}</p>}{item.due_date&&<span className={'due-badge '+(!item.done&&item.due_date<today?'overdue':'')}>{!item.done&&item.due_date<today?'Overdue · ':''}{new Date(item.due_date+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</span>}</div><div className="item-actions"><button aria-label={'Move '+item.title+' up'} title="Move up" disabled={busy||index===0} onClick={()=>move(index,index-1)}>↑</button><button aria-label={'Move '+item.title+' down'} title="Move down" disabled={busy||index===list.length-1} onClick={()=>move(index,index+1)}>↓</button><button aria-label={'Edit '+item.title} title="Edit" disabled={busy} onClick={()=>edit(item)}>✎</button><button aria-label={'Delete '+item.title} title="Delete" disabled={busy} onClick={()=>{if(confirm('Delete “'+item.title+'”?'))act(async()=>{await api('/items/'+item.id,'DELETE');if(editing?.id===item.id){setEditing(null);setDraft(blank);}});}}>×</button></div></article>)}</div>}</section><footer>Less clutter. More headspace.</footer></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);

